apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-operator
  annotations:
    argocd.argoproj.io/sync-wave: "250"
  labels:
    gitops.tier.group: cntk
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: sealed-secrets
    server: 'https://kubernetes.default.svc'
  project: services
  source:
    path: sealed-secrets
    repoURL: https://github.com/csantanapr/test-sealed.git
    targetRevision: main
    helm:
      values: |
        sealed-secrets:
          commandArgs:
            - "--update-status"
